version: "3.2"
services:
  rabbitmq:
    build: .
    ports:
        - 5672:5672
        - 15672:15672
        - 61613:61613
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest